sudo: required
language: c
compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libglib2.0-dev
      - peg
      - valgrind

env:
  - TARGET=distcheck
  - TARGET=valgrind

before_script:
  - git fetch --unshallow
  - ./autogen.sh

script:
  - ./.travis/build.sh
  - ./.travis/deploy.sh
