language: c

compiler:
  - gcc
  - clang

env:
  - PEG_RELEASE=0.1.15 GLIB_RELEASE=2.34.3
  - PEG_RELEASE=0.1.15 GLIB_RELEASE=2.38.2
  - PEG_RELEASE=0.1.15 GLIB_RELEASE=2.40.0
  - PEG_RELEASE=0.1.15 GLIB_RELEASE=2.41.0

before_install:
  - sudo apt-get install -y libfcgi-dev valgrind

install:
  - ./.travis-install.sh "0.1" "${PEG_RELEASE}"

script:
  - ./.travis.sh "${GLIB_RELEASE}" "${PEG_RELEASE}"
