language: c

compiler:
  - gcc
  - clang

env:
  - PEG_VERSION=0.1.15 GLIB_VERSION=2.34 GLIB_RELEASE=2.34.3
  - PEG_VERSION=0.1.15 GLIB_VERSION=2.38 GLIB_RELEASE=2.38.2
  - PEG_VERSION=0.1.15 GLIB_VERSION=2.40 GLIB_RELEASE=2.40.0

before_install:
  - sudo apt-get install -y libfcgi-dev libmagic-dev
  - wget "http://ftp.gnome.org/pub/gnome/sources/glib/$GLIB_VERSION/glib-$GLIB_RELEASE.tar.xz"
  - tar -xvf "glib-$GLIB_RELEASE.tar.xz" -C ~
  - mkdir -p ~/glib/build
  - pushd ~/glib/build > /dev/null && ~/glib-$GLIB_RELEASE/configure && popd > /dev/null
  - make -C ~/glib/build
  - wget "http://piumarta.com/software/peg/peg-$PEG_VERSION.tar.gz"
  - tar -xvf "peg-$PEG_VERSION.tar.gz" -C ~
  - make -C ~/peg-$PEG_VERSION/

install:
  - sudo make -C ~/glib/build install
  - sudo make -C ~/peg-$PEG_VERSION/ install

script:
  - export BALDE_DIR="$(pwd)"
  - ./autogen.sh
  - mkdir -p ~/balde-build
  - pushd ~/balde-build > /dev/null && $BALDE_DIR/configure --enable-examples --with-leg && popd > /dev/null
  - make -C ~/balde-build check
