dist: xenial
language: c

matrix:
  include:
    - compiler: gcc
      env:
        - TARGET=distcheck
      addons:
        apt:
          packages:
            - libglib2.0-dev
            - libxml2-utils
            - peg
    - compiler: clang
      env:
        - TARGET=distcheck
        - DISABLE_PUBLISHER=1
      addons:
        apt:
          packages:
            - libglib2.0-dev
            - libxml2-utils
            - peg
    - compiler: gcc
      env:
        - TARGET=valgrind
      addons:
        apt:
          packages:
            - libglib2.0-dev
            - libxml2-utils
            - peg
            - valgrind
    - compiler: clang
      env:
        - TARGET=valgrind
      addons:
        apt:
          packages:
            - libglib2.0-dev
            - libxml2-utils
            - peg
            - valgrind
    - compiler: gcc
      env:
        - TARGET=dist-docs
      addons:
        apt:
          packages:
            - libglib2.0-dev
            - libxml2-utils
            - peg
            - doxygen

script: curl -sSf https://yatr.rgm.io/run.sh | bash
