dist: xenial
language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libglib2.0-dev
      - libxml2-utils
      - peg
      - valgrind
      - realpath

env:
  - TARGET=distcheck
  - TARGET=valgrind

script: curl -sSf https://yatr.rgm.io/run.sh | bash
