language: c

compiler:
  - gcc
  - clang

env:
  - GLIB_VERSION=2.34.3

before_install:
  - wget http://ftp.gnome.org/pub/gnome/sources/glib/2.34/glib-$GLIB_VERSION.tar.xz
  - tar -xvf glib-$GLIB_VERSION.tar.xz -C ~
  - mkdir -p ~/glib/build
  - pushd ~/glib/build > /dev/null && ~/glib-$GLIB_VERSION/configure && popd > /dev/null
  - make -C ~/glib/build

install:
  - sudo make -C ~/glib/build install

script:
  - ./autogen.sh
  - mkdir -p ~/balde-build
  - pushd ~/balde-build > /dev/null && ./configure --enable-examples && popd > /dev/null
  - make -C ~/balde-build check
