default_configure_args:
  - "CFLAGS=-O0 -g -Wall"
  - --disable-silent-rules
  - --enable-examples
  - --enable-leg
  - --disable-valgrind
  - --disable-doc

targets:
  dist-docs:
    configure_args:
      - --enable-doc
      - --disable-tests
    archive_extract_filter: "*.tar.xz"
  valgrind:
    configure_args:
      - --enable-valgrind
