default_configure_args:
  - "CFLAGS=-O0 -g -Wall"
  - --disable-silent-rules
  - --enable-examples
  - --enable-http
  - --enable-leg
  - --disable-valgrind
  - --disable-doc

targets:
  valgrind:
    configure_args:
      - --enable-valgrind
